export default {
  CHANGE: "CHANGE",
  LOGIN: "LOGIN",
  CLEARUSERDATA: "CLEARUSERDATA",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  CHANGE: "CHANGE",

  TABLE_CHEQUE_UPDATED: "TABLE_CHEQUE_UPDATED",
  TABLE_ADMINISTRATIF_UPDATED: "TABLE_ADMINISTRATIF_UPDATED",
  TABLE_PERMANENT_UPDATED: "TABLE_PERMANENT_UPDATED",
  TABLE_SAISONIER_UPDATED: "TABLE_SAISONIER_UPDATED",
  TABLE_CONSOMABLE_UPDATED: "TABLE_CONSOMABLE_UPDATED",
  TYPE_STOCK_SELECT: "TYPE_STOCK_SELECT",
  TYPE_PERSONNEL_SELECT: "TYPE_PERSONNEL_SELECT",
  TABLE_NON_CONSOMABLE_UPDATED: "TABLE_NON_CONSOMABLE_UPDATED"
};
