export default {
  CHANGE: "CHANGE",
  LOGIN: "LOGIN",
  CLEARUSERDATA: "CLEARUSERDATA",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",

  TABLE_CHEQUE_UPDATED: "TABLE_CHEQUE_UPDATED",
  TABLE_CONSOMABLE_UPDATED: "TABLE_CONSOMABLE_UPDATED",
  TYPE_STOCK_SELECT: "TYPE_STOCK_SELECT",
  TABLE_NON_CONSOMABLE_UPDATED: "TABLE_NON_CONSOMABLE_UPDATED"
};
